Repository AY2324S1-CS2103T-T08-2/tp, pull requests merged in 2023-11, with the labels that each got.

#160 Implement shortcuts and fix storage bug
  src/main/java/networkbook/logic/LogicManager.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/ClearCommand.java
  src/main/java/networkbook/logic/commands/Command.java
  src/main/java/networkbook/logic/commands/CreateCommand.java
  src/main/java/networkbook/logic/commands/ExitCommand.java
  src/main/java/networkbook/logic/commands/FindCommand.java
  src/main/java/networkbook/logic/commands/HelpCommand.java
  src/main/java/networkbook/logic/commands/ListCommand.java
  src/main/java/networkbook/logic/commands/OpenLinkCommand.java
  src/main/java/networkbook/logic/commands/RedoCommand.java
  src/main/java/networkbook/logic/commands/SaveCommand.java
  src/main/java/networkbook/logic/commands/SortCommand.java
  src/main/java/networkbook/logic/commands/UndoCommand.java
  src/main/java/networkbook/logic/commands/delete/DeleteFieldCommand.java
  src/main/java/networkbook/logic/commands/delete/DeletePersonCommand.java
  src/main/java/networkbook/logic/commands/edit/EditCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterCommand.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/main/java/networkbook/ui/CommandBox.java
  src/main/java/networkbook/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/networkbook/logic/LogicManagerTest.java
  src/test/java/networkbook/logic/commands/CommandResultTest.java
  src/test/java/networkbook/logic/commands/SaveCommandTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/ui/CommandBoxTest.java
  src/test/java/networkbook/ui/MainWindowTest.java
Labels: type.Story, type.Bug, priority.High, severity.High

#163 Update phone regex - Nguyen
  src/main/java/networkbook/model/person/Phone.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/model/person/PhoneTest.java
  src/test/java/networkbook/storage/JsonAdaptedPersonTest.java
Labels: type.Enhancement

#170 Fix bug in OpenEmailCommand
  src/main/java/networkbook/logic/commands/OpenEmailCommand.java
Labels: type.Bug, priority.High

#164 Update tag regex - Nguyen
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/model/person/Tag.java
  src/test/java/networkbook/model/person/TagTest.java
Labels: type.Enhancement

#165 Implement adding and editing courses with start and end dates
  src/main/java/networkbook/logic/parser/ArgumentMultimap.java
  src/main/java/networkbook/logic/parser/CliSyntax.java
  src/main/java/networkbook/logic/parser/CreateCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/model/person/Course.java
  src/test/java/networkbook/logic/parser/AddCommandParserTest.java
  src/test/java/networkbook/logic/parser/CreateCommandParserTest.java
  src/test/java/networkbook/logic/parser/EditCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
Labels: priority.High

#169 Add undo/redo to displayed contacts
  docs/UserGuide.md
  src/main/java/networkbook/logic/LogicManager.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/CreateCommand.java
  src/main/java/networkbook/logic/commands/FindCommand.java
  src/main/java/networkbook/logic/commands/ListCommand.java
  src/main/java/networkbook/logic/commands/OpenEmailCommand.java
  src/main/java/networkbook/logic/commands/OpenLinkCommand.java
  src/main/java/networkbook/logic/commands/RedoCommand.java
  src/main/java/networkbook/logic/commands/SortCommand.java
  src/main/java/networkbook/logic/commands/UndoCommand.java
  src/main/java/networkbook/logic/commands/delete/DeleteFieldCommand.java
  src/main/java/networkbook/logic/commands/delete/DeletePersonCommand.java
  src/main/java/networkbook/logic/commands/edit/EditCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterCourseCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterGradCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterSpecCommand.java
  src/main/java/networkbook/model/Model.java
  src/main/java/networkbook/model/ModelManager.java
  src/main/java/networkbook/model/NetworkBook.java
  src/main/java/networkbook/model/ReadOnlyNetworkBook.java
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/commands/CreateCommandIntegrationTest.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
  src/test/java/networkbook/logic/commands/FindCommandTest.java
  src/test/java/networkbook/logic/commands/OpenEmailCommandTest.java
  src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java
  src/test/java/networkbook/logic/commands/SortCommandTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteFieldCommandTest.java
  src/test/java/networkbook/logic/commands/delete/DeletePersonCommandTest.java
  src/test/java/networkbook/logic/commands/edit/EditCommandTest.java
  src/test/java/networkbook/logic/commands/filter/FilterCourseCommandTest.java
  src/test/java/networkbook/logic/commands/filter/FilterGradCommandTest.java
  src/test/java/networkbook/logic/commands/filter/FilterSpecCommandTest.java
  src/test/java/networkbook/model/ModelManagerTest.java
  src/test/java/networkbook/model/NetworkBookTest.java
  src/test/java/networkbook/model/VersionedNetworkBookTest.java
  src/test/java/networkbook/testutil/TestUtil.java
  src/test/java/networkbook/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#174 Make `/index` optional for `edit` and `delete`
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/OpenEmailCommand.java
  src/main/java/networkbook/logic/commands/OpenLinkCommand.java
  src/main/java/networkbook/logic/commands/delete/DeleteCourseAction.java
  src/main/java/networkbook/logic/commands/delete/DeleteEmailAction.java
  src/main/java/networkbook/logic/commands/delete/DeleteFieldAction.java
  src/main/java/networkbook/logic/commands/delete/DeleteFieldCommand.java
  src/main/java/networkbook/logic/commands/delete/DeleteGraduationAction.java
  src/main/java/networkbook/logic/commands/delete/DeleteLinkAction.java
  src/main/java/networkbook/logic/commands/delete/DeletePersonDescriptor.java
  src/main/java/networkbook/logic/commands/delete/DeletePhoneAction.java
  src/main/java/networkbook/logic/commands/delete/DeletePriorityAction.java
  src/main/java/networkbook/logic/commands/delete/DeleteSpecialisationAction.java
  src/main/java/networkbook/logic/commands/delete/DeleteTagAction.java
  src/main/java/networkbook/logic/commands/edit/EditAction.java
  src/main/java/networkbook/logic/commands/edit/EditCommand.java
  src/main/java/networkbook/logic/commands/edit/EditCourseAction.java
  src/main/java/networkbook/logic/commands/edit/EditEmailAction.java
  src/main/java/networkbook/logic/commands/edit/EditGraduationAction.java
  src/main/java/networkbook/logic/commands/edit/EditLinkAction.java
  src/main/java/networkbook/logic/commands/edit/EditNameAction.java
  src/main/java/networkbook/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/networkbook/logic/commands/edit/EditPhoneAction.java
  src/main/java/networkbook/logic/commands/edit/EditPriorityAction.java
  src/main/java/networkbook/logic/commands/edit/EditSpecialisationAction.java
  src/main/java/networkbook/logic/commands/edit/EditTagAction.java
  src/main/java/networkbook/logic/parser/ArgumentMultimap.java
  src/main/java/networkbook/logic/parser/DeleteCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/test/java/networkbook/logic/commands/OpenEmailCommandTest.java
  src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteCourseActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteEmailActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteFieldCommandTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteGraduationActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteLinkActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeletePhoneActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeletePriorityActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteSpecialisationActionTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteTagActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditCommandTest.java
  src/test/java/networkbook/logic/commands/edit/EditCourseActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditEmailActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditGraduationActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditLinkActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditNameActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/networkbook/logic/commands/edit/EditPhoneActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditPriorityActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditSpecialisationActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditTagActionTest.java
  src/test/java/networkbook/logic/parser/DeleteCommandParserTest.java
  src/test/java/networkbook/logic/parser/EditCommandParserTest.java
Labels: type.Enhancement, priority.High

#175 Update `delete` command and shortcuts in UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#176 Fix sort field constraints message
  src/main/java/networkbook/model/person/PersonSortComparator.java
Labels: type.Bug, severity.Medium

#180 Open email & link bug fix - Nguyen
  src/main/java/networkbook/model/NetworkBook.java
Labels: type.Bug, priority.High, severity.High

#178 UI tweaks
  docs/UserGuide.md
  src/main/java/networkbook/logic/commands/FilterCommandResult.java
  src/main/java/networkbook/logic/commands/ListCommand.java
  src/main/java/networkbook/logic/commands/ListCommandResult.java
  src/main/java/networkbook/logic/commands/SortCommand.java
  src/main/java/networkbook/logic/commands/SortCommandResult.java
  src/main/java/networkbook/logic/commands/filter/FilterCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterCourseCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterGradCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterSpecCommand.java
  src/main/java/networkbook/logic/commands/filter/FilterTagCommand.java
  src/main/java/networkbook/logic/parser/FilterCommandParser.java
  src/main/java/networkbook/model/person/PersonSortComparator.java
  src/main/java/networkbook/ui/MainWindow.java
  src/main/java/networkbook/ui/PersonCard.java
  src/main/java/networkbook/ui/StatusBarFooter.java
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: type.Enhancement

#183 Update user-facing documentation in preparation for PE-D
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/add-remark/add-phone.png
  docs/images/create/create.png
  docs/images/delete/delete.png
  docs/images/edit/edit.png
  docs/images/filter/filter.png
  docs/images/filter/filterSuccess.PNG
  docs/images/find/find.png
  docs/images/find/search-success.png
  docs/images/gui-annotated.png
  docs/images/open/open-email.png
  docs/images/open/open-link.png
  docs/images/sort/sort.png
  docs/index.md
Labels: type.Task

#221 Refactor add command
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/add/AddCommand.java
  src/main/java/networkbook/logic/commands/add/AddPersonDescriptor.java
  src/main/java/networkbook/logic/parser/AddCommandParser.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/commands/add/AddCommandTest.java
  src/test/java/networkbook/logic/commands/add/AddPersonDescriptorTest.java
  src/test/java/networkbook/logic/parser/AddCommandParserTest.java
  src/test/java/networkbook/testutil/AddPersonDescriptorBuilder.java
Labels: type.Task

#222 Delete `Address` class
  src/main/java/networkbook/MainApp.java
  src/main/java/networkbook/logic/commands/ExitCommand.java
  src/main/java/networkbook/model/person/Address.java
  src/test/java/networkbook/model/person/AddressTest.java
Labels: type.Task

#239 Change target throwing CommandException
  src/main/java/networkbook/logic/commands/RedoCommand.java
  src/main/java/networkbook/logic/commands/UndoCommand.java
  src/main/java/networkbook/model/Model.java
  src/main/java/networkbook/model/ModelManager.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
  src/test/java/networkbook/logic/commands/OpenEmailCommandTest.java
  src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java
  src/test/java/networkbook/logic/commands/RedoCommandTest.java
  src/test/java/networkbook/model/ModelManagerTest.java
Labels: priority.High

#242 Remove misleading message of index where contact is created
  src/main/java/networkbook/logic/commands/CreateCommand.java
  src/test/java/networkbook/logic/commands/CreateCommandIntegrationTest.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
Labels: type.Task, priority.Medium

#243 Amend phrasing of branch phone constraints message in application
  src/main/java/networkbook/model/person/Phone.java
Labels: type.Task, priority.Medium

#241 Fix displayed list reverting bug
  src/main/java/networkbook/model/NetworkBook.java
  src/test/java/networkbook/model/VersionedNetworkBookTest.java
Labels: type.Task, priority.High

#254 Fix shortcut not working issue on macOS
  src/main/java/networkbook/ui/CommandBox.java
  src/main/java/networkbook/ui/KeyboardShortcutUtil.java
  src/main/java/networkbook/ui/MainWindow.java
  src/test/java/networkbook/ui/KeyboardShortcutUtilTest.java
Labels: type.Bug, priority.High

#259 Remove changes risking feature freeze
  src/main/java/networkbook/model/person/Phone.java
Labels: type.Task, priority.High

#238 Update PPP - Nguyen
  docs/team/nknguyenhc.md
Labels: type.Task

#256 Add clarification to undo/redo features
  docs/UserGuide.md
Labels: priority.High

#255 Update HB's PPP to draft version
  docs/team/awhb.md
Labels: type.Task, priority.Medium

#261 Suppress unchecked warning
  src/main/java/networkbook/model/NetworkBook.java
Labels: type.Bug, priority.High

#245 Update DG - Nguyen
  docs/DeveloperGuide.md
  docs/diagrams/EditDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/OpenDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/edit/EditDiagram.png
  docs/images/open/OpenDiagram.png
  src/main/java/networkbook/model/person/Person.java
Labels: type.Task

#266 Update DG: Hang Bin
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/CreateDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/create/CreateDiagram.png
Labels: type.Task, priority.High

#248 Update planned enhancements
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#290 Fix contact duplicate checking issue
  src/main/java/networkbook/model/person/Name.java
  src/test/java/networkbook/model/person/NameTest.java
  src/test/java/networkbook/model/person/PersonTest.java
Labels: type.Bug

#286 Fix error message of invalid index of entry
  docs/UserGuide.md
  src/main/java/networkbook/logic/parser/AddCommandParser.java
  src/main/java/networkbook/logic/parser/DeleteCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/OpenEmailCommandParser.java
  src/main/java/networkbook/logic/parser/OpenLinkCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/parser/AddCommandParserTest.java
  src/test/java/networkbook/logic/parser/DeleteCommandParserTest.java
  src/test/java/networkbook/logic/parser/EditCommandParserTest.java
  src/test/java/networkbook/logic/parser/OpenEmailCommandParserTest.java
  src/test/java/networkbook/logic/parser/OpenLinkCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
Labels: type.Bug, priority.High
