Repository AY2324S1-CS2103T-T08-2/tp, pull requests merged in 2023-10, with the labels that each got.

#21 Update project readme
  README.md
Labels: type.Task

#19 Add Nguyen's PPP
  docs/team/nknguyenhc.md
Labels: type.Task, priority.High

#24 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#33 Update about us page
  docs/AboutUs.md
  docs/images/awhb.png
Labels: type.Task

#35 Add HB's Skeletal PPP
  docs/team/awhb.md
Labels: type.Task

#34 Update user guide
  docs/UserGuide.md
  docs/images/find/search-success.png
Labels: type.Task, priority.High

#52 Branch update dg
  docs/DeveloperGuide.md
Labels: priority.High

#57 Update UG - Nguyen
  docs/UserGuide.md
Labels: type.Task, priority.High

#79 Add generic unique list class
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/EditCommand.java
  src/main/java/networkbook/logic/parser/AddCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/model/Model.java
  src/main/java/networkbook/model/ModelManager.java
  src/main/java/networkbook/model/NetworkBook.java
  src/main/java/networkbook/model/person/Email.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/model/person/UniquePersonList.java
  src/main/java/networkbook/model/person/exceptions/DuplicateException.java
  src/main/java/networkbook/model/person/exceptions/DuplicatePersonException.java
  src/main/java/networkbook/model/person/exceptions/ItemNotFoundException.java
  src/main/java/networkbook/model/person/exceptions/PersonNotFoundException.java
  src/main/java/networkbook/model/tag/Tag.java
  src/main/java/networkbook/model/util/Identifiable.java
  src/main/java/networkbook/model/util/SampleDataUtil.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/main/java/networkbook/storage/JsonAdaptedPerson.java
  src/main/java/networkbook/storage/JsonAdaptedProperty.java
  src/main/java/networkbook/storage/JsonAdaptedTag.java
  src/main/java/networkbook/ui/PersonCard.java
  src/test/data/JsonNetworkBookStorageTest/invalidAndValidPersonNetworkBook.json
  src/test/data/JsonNetworkBookStorageTest/invalidPersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/duplicatePersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/invalidPersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/typicalPersonsNetworkBook.json
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/EditCommandTest.java
  src/test/java/networkbook/logic/commands/EditPersonDescriptorTest.java
  src/test/java/networkbook/model/NetworkBookTest.java
  src/test/java/networkbook/model/person/EmailTest.java
  src/test/java/networkbook/model/person/PersonTest.java
  src/test/java/networkbook/model/person/UniquePersonListTest.java
  src/test/java/networkbook/model/tag/TagTest.java
  src/test/java/networkbook/model/util/UniqueListTest.java
  src/test/java/networkbook/model/util/UniqueNumber.java
  src/test/java/networkbook/storage/JsonAdaptedPersonTest.java
  src/test/java/networkbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/PersonBuilder.java
  src/test/java/networkbook/testutil/PersonUtil.java
Labels: type.Task, priority.High

#87 Update person attributes
  docs/DeveloperGuide.md
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/CreateCommand.java
  src/main/java/networkbook/logic/commands/EditCommand.java
  src/main/java/networkbook/logic/parser/AddCommandParser.java
  src/main/java/networkbook/logic/parser/CliSyntax.java
  src/main/java/networkbook/logic/parser/CreateCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/model/NetworkBook.java
  src/main/java/networkbook/model/person/Address.java
  src/main/java/networkbook/model/person/Course.java
  src/main/java/networkbook/model/person/GraduatingYear.java
  src/main/java/networkbook/model/person/Link.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/model/person/Specialisation.java
  src/main/java/networkbook/model/util/SampleDataUtil.java
  src/main/java/networkbook/storage/JsonAdaptedPerson.java
  src/main/java/networkbook/ui/PersonCard.java
  src/test/data/JsonNetworkBookStorageTest/invalidAndValidPersonNetworkBook.json
  src/test/data/JsonNetworkBookStorageTest/invalidPersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/duplicatePersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/invalidPersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/typicalPersonsNetworkBook.json
  src/test/java/networkbook/logic/LogicManagerTest.java
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/commands/EditPersonDescriptorTest.java
  src/test/java/networkbook/logic/parser/AddCommandParserTest.java
  src/test/java/networkbook/logic/parser/CreateCommandParserTest.java
  src/test/java/networkbook/logic/parser/EditCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/model/NetworkBookTest.java
  src/test/java/networkbook/model/person/CourseTest.java
  src/test/java/networkbook/model/person/GraduatingYearTest.java
  src/test/java/networkbook/model/person/LinkTest.java
  src/test/java/networkbook/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/networkbook/model/person/PersonTest.java
  src/test/java/networkbook/model/person/SpecialisationTest.java
  src/test/java/networkbook/storage/JsonAdaptedPersonTest.java
  src/test/java/networkbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/PersonBuilder.java
  src/test/java/networkbook/testutil/PersonUtil.java
  src/test/java/networkbook/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#85 Finish up Priority
  build.gradle
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/model/person/Priority.java
  src/main/java/networkbook/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/model/person/PriorityTest.java
  src/test/java/networkbook/ui/HeadlessHelper.java
  src/test/java/networkbook/ui/PersonCardTest.java
Labels: type.Story, priority.High

#86 Add email
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/parser/AddCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/test/java/networkbook/logic/parser/AddCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/model/util/UniqueListTest.java
Labels: type.Task, priority.High

#89 Implement create contact command
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/EditCommand.java
  src/main/java/networkbook/logic/parser/CreateCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/storage/JsonAdaptedPerson.java
  src/main/java/networkbook/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/parser/CreateCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/model/person/PersonTest.java
  src/test/java/networkbook/storage/JsonAdaptedPersonTest.java
  src/test/java/networkbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/PersonBuilder.java
  src/test/java/networkbook/testutil/PersonUtil.java
  src/test/java/networkbook/ui/PersonCardTest.java
Labels: type.Task, priority.High

#91 Branch add phone
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/EditCommand.java
  src/main/java/networkbook/logic/parser/CreateCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/model/person/Phone.java
  src/main/java/networkbook/model/util/SampleDataUtil.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/main/java/networkbook/storage/JsonAdaptedPerson.java
  src/main/java/networkbook/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonNetworkBookStorageTest/invalidAndValidPersonNetworkBook.json
  src/test/data/JsonNetworkBookStorageTest/invalidPersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/duplicatePersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/invalidPersonNetworkBook.json
  src/test/data/JsonSerializableNetworkBookTest/typicalPersonsNetworkBook.json
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/commands/EditCommandTest.java
  src/test/java/networkbook/logic/commands/EditPersonDescriptorTest.java
  src/test/java/networkbook/logic/parser/CreateCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/networkbook/model/person/PersonTest.java
  src/test/java/networkbook/model/util/UniqueListTest.java
  src/test/java/networkbook/storage/JsonAdaptedPersonTest.java
  src/test/java/networkbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/PersonBuilder.java
  src/test/java/networkbook/testutil/PersonUtil.java
  src/test/java/networkbook/testutil/TypicalPersons.java
  src/test/java/networkbook/ui/PersonCardTest.java
Labels: type.Task, priority.High

#97 Jiale/tag
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/EditCommand.java
  src/main/java/networkbook/logic/parser/CreateCommandParser.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/model/tag/Tag.java
  src/main/java/networkbook/model/util/SampleDataUtil.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/main/java/networkbook/storage/JsonAdaptedPerson.java
  src/main/java/networkbook/ui/PersonCard.java
  src/test/java/networkbook/logic/commands/EditPersonDescriptorTest.java
  src/test/java/networkbook/logic/parser/CreateCommandParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/model/person/PersonTest.java
  src/test/java/networkbook/model/tag/TagTest.java
  src/test/java/networkbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/PersonBuilder.java
  src/test/java/networkbook/testutil/PersonUtil.java
Labels: type.Story, priority.High

#98 Remove duplicate grad prefix definition
  src/main/java/networkbook/logic/parser/CliSyntax.java
Labels: type.Bug, priority.Medium, severity.Low

#94 Implement contacts sorting feature
  docs/UserGuide.md
  src/main/java/networkbook/logic/commands/SortCommand.java
  src/main/java/networkbook/logic/parser/CliSyntax.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/main/java/networkbook/logic/parser/ParserUtil.java
  src/main/java/networkbook/logic/parser/SortCommandParser.java
  src/main/java/networkbook/model/Model.java
  src/main/java/networkbook/model/ModelManager.java
  src/main/java/networkbook/model/person/Name.java
  src/main/java/networkbook/model/person/PersonSortComparator.java
  src/main/java/networkbook/model/person/Priority.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
  src/test/java/networkbook/logic/commands/SortCommandTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/logic/parser/ParserUtilTest.java
  src/test/java/networkbook/logic/parser/SortCommandParserTest.java
  src/test/java/networkbook/model/ModelManagerTest.java
  src/test/java/networkbook/model/person/PersonSortComparatorTest.java
Labels: type.Task, priority.High

#100 Delete command
  src/main/java/networkbook/logic/commands/DeleteCommand.java
  src/test/java/networkbook/logic/commands/DeleteCommandTest.java
Labels: type.Story, priority.High

#99 Add testcases for find command
  src/test/java/networkbook/logic/commands/FindCommandTest.java
Labels: type.Task, priority.High

#102 Enable search by fragment of contact name
  src/main/java/networkbook/commons/util/StringUtil.java
  src/main/java/networkbook/logic/commands/FindCommand.java
  src/main/java/networkbook/logic/parser/FindCommandParser.java
  src/main/java/networkbook/model/person/NameContainsKeyTermsPredicate.java
  src/test/java/networkbook/commons/util/StringUtilTest.java
  src/test/java/networkbook/logic/commands/FindCommandTest.java
  src/test/java/networkbook/logic/parser/FindCommandParserTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/model/person/NameContainsKeyTermsPredicateTest.java
Labels: type.Task, priority.High

#105 Check and fix potential flaws in DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#104 Fix link
  src/main/java/networkbook/model/person/Link.java
  src/test/java/networkbook/model/person/LinkTest.java
Labels: type.Bug, priority.High

#103 Standardise CommandResult Messages to match the UG
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/ClearCommand.java
  src/main/java/networkbook/logic/commands/CreateCommand.java
  src/main/java/networkbook/logic/commands/DeleteCommand.java
  src/main/java/networkbook/logic/commands/FindCommand.java
  src/main/java/networkbook/logic/commands/ListCommand.java
  src/main/java/networkbook/logic/commands/SortCommand.java
  src/main/java/networkbook/model/person/NameContainsKeyTermsPredicate.java
  src/test/java/networkbook/logic/LogicManagerTest.java
  src/test/java/networkbook/logic/commands/CreateCommandIntegrationTest.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
  src/test/java/networkbook/logic/commands/DeleteCommandTest.java
  src/test/java/networkbook/logic/commands/FindCommandTest.java
  src/test/java/networkbook/logic/commands/ListCommandTest.java
  src/test/java/networkbook/logic/commands/SortCommandTest.java
Labels: type.Task, priority.Medium

#96 Update UG to match command implementations
  docs/UserGuide.md
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/DeleteCommand.java
  src/main/java/networkbook/logic/commands/EditCommand.java
Labels: type.Task, priority.High

#124 Reformat user guide headings
  docs/UserGuide.md
Labels: priority.High

#122 Edit command - Nguyen
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/tutorials/TracingCode.md
  src/main/java/networkbook/logic/Messages.java
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/EditCommand.java
  src/main/java/networkbook/logic/commands/edit/EditAction.java
  src/main/java/networkbook/logic/commands/edit/EditCommand.java
  src/main/java/networkbook/logic/commands/edit/EditCourseAction.java
  src/main/java/networkbook/logic/commands/edit/EditEmailAction.java
  src/main/java/networkbook/logic/commands/edit/EditGraduationAction.java
  src/main/java/networkbook/logic/commands/edit/EditLinkAction.java
  src/main/java/networkbook/logic/commands/edit/EditNameAction.java
  src/main/java/networkbook/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/networkbook/logic/commands/edit/EditPhoneAction.java
  src/main/java/networkbook/logic/commands/edit/EditPriorityAction.java
  src/main/java/networkbook/logic/commands/edit/EditSpecialisationAction.java
  src/main/java/networkbook/logic/commands/edit/EditTagAction.java
  src/main/java/networkbook/logic/parser/AddCommandParser.java
  src/main/java/networkbook/logic/parser/ArgumentMultimap.java
  src/main/java/networkbook/logic/parser/CliSyntax.java
  src/main/java/networkbook/logic/parser/EditCommandParser.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/main/java/networkbook/ui/PersonCard.java
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/AddPersonDescriptorTest.java
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/commands/EditCommandTest.java
  src/test/java/networkbook/logic/commands/edit/EditCommandTest.java
  src/test/java/networkbook/logic/commands/edit/EditCommandUtil.java
  src/test/java/networkbook/logic/commands/edit/EditCourseActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditEmailActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditGraduationActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditLinkActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditNameActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/networkbook/logic/commands/edit/EditPhoneActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditPriorityActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditSpecialisationActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditTagActionTest.java
  src/test/java/networkbook/logic/parser/AddCommandParserTest.java
  src/test/java/networkbook/logic/parser/EditCommandParserTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/testutil/AddPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/EditPersonDescriptorBuilder.java
  src/test/java/networkbook/testutil/PersonUtil.java
  src/test/java/networkbook/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#128 Write product overview section
  docs/UserGuide.md
Labels: priority.High

#132 Update UG's command summary and FAQ
  docs/UserGuide.md
Labels: type.Task, priority.High

#135 Fix font and grammar issues
  docs/UserGuide.md
Labels: type.Task, priority.High

#136 Enable assertion
  build.gradle
Labels: type.Task, priority.High

#141 Implement Filter Course
  src/main/java/networkbook/logic/commands/filter/FilterCommand.java
  src/main/java/networkbook/logic/parser/CliSyntax.java
  src/main/java/networkbook/logic/parser/FilterCommandParser.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/main/java/networkbook/model/person/filter/CourseContainsKeyTermsPredicate.java
  src/main/java/networkbook/model/person/filter/CourseIsStillBeingTakenPredicate.java
  src/test/java/networkbook/logic/commands/FilterCommandTest.java
  src/test/java/networkbook/logic/parser/FilterCommandParserTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/model/person/CourseContainsKeyTermsPredicateTest.java
  src/test/java/networkbook/model/person/CourseIsStillBeingTakenPredicateTest.java
  src/test/java/networkbook/testutil/PersonBuilder.java
Labels: priority.High

#149 Update Logic section of DG and own PPP
  docs/DeveloperGuide.md
  docs/team/eola-z.md
Labels: type.Task

#138 Update edit sequence - Nguyen
  docs/DeveloperGuide.md
  docs/diagrams/EditDiagram.puml
  docs/images/edit/EditDiagram.png
Labels: type.Task, priority.High

#148 Update documentation
  docs/DeveloperGuide.md
  docs/team/xenosf.md
Labels: type.Task, priority.High

#151 Update DG with design details for CreateCommand
  docs/DeveloperGuide.md
  docs/diagrams/CreateDiagram.puml
  docs/images/create/CreateDiagram.png
Labels: type.Task, priority.High

#147 Command check duplicates
  src/main/java/networkbook/logic/commands/AddCommand.java
  src/main/java/networkbook/logic/commands/edit/EditPersonDescriptor.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/test/java/networkbook/logic/commands/AddCommandTest.java
  src/test/java/networkbook/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/networkbook/model/util/UniqueListTest.java
Labels: type.Bug, priority.High, severity.High

#152 Open link - Nguyen
  src/main/java/networkbook/commons/util/ThrowingIoExceptionConsumer.java
  src/main/java/networkbook/logic/commands/OpenLinkCommand.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/main/java/networkbook/logic/parser/OpenLinkCommandParser.java
  src/main/java/networkbook/model/Model.java
  src/main/java/networkbook/model/ModelManager.java
  src/main/java/networkbook/model/NetworkBook.java
  src/main/java/networkbook/model/person/Link.java
  src/main/java/networkbook/model/person/Person.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/test/data/JsonSerializableNetworkBookTest/typicalPersonsNetworkBook.json
  src/test/java/networkbook/logic/commands/CommandTestUtil.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
  src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java
  src/test/java/networkbook/logic/commands/delete/DeleteLinkActionTest.java
  src/test/java/networkbook/logic/commands/edit/EditPersonDescriptorTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/logic/parser/OpenLinkCommandParserTest.java
  src/test/java/networkbook/model/person/LinkTest.java
  src/test/java/networkbook/model/person/PersonTest.java
  src/test/java/networkbook/model/util/ThrowingIoExceptionConsumerManager.java
  src/test/java/networkbook/model/util/UniqueListTest.java
  src/test/java/networkbook/testutil/TypicalIndexes.java
  src/test/java/networkbook/testutil/TypicalPersons.java
Labels: type.Story, priority.High

#145 Branch revertible data
  src/main/java/networkbook/logic/commands/RedoCommand.java
  src/main/java/networkbook/logic/commands/UndoCommand.java
  src/main/java/networkbook/logic/parser/NetworkBookParser.java
  src/main/java/networkbook/model/Model.java
  src/main/java/networkbook/model/ModelManager.java
  src/main/java/networkbook/model/NetworkBook.java
  src/main/java/networkbook/model/VersionedNetworkBook.java
  src/main/java/networkbook/model/util/UniqueList.java
  src/test/java/networkbook/logic/commands/CreateCommandTest.java
  src/test/java/networkbook/logic/commands/OpenLinkCommandTest.java
  src/test/java/networkbook/logic/commands/RedoCommandTest.java
  src/test/java/networkbook/logic/commands/UndoCommandTest.java
  src/test/java/networkbook/logic/parser/NetworkBookParserTest.java
  src/test/java/networkbook/model/ModelManagerTest.java
  src/test/java/networkbook/model/NetworkBookTest.java
  src/test/java/networkbook/model/VersionedNetworkBookTest.java
Labels: type.Story, priority.High
